name: Rerun Check ServiceNow Approval
run-name: Rerunning Check ServiceNow Approval
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
concurrency:
  group: rerun-check-servicenow-approval
  cancel-in-progress: false
jobs:
  rerun-check-servicenow-approval:
    name: Rerun Check ServiceNow Approval
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Rerun Check ServiceNow Approval
        run: .github/actions/rerun-check-servicenow-approval
        env:
          GITHUB_OWNER: ${{ github.repository_owner }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO: ${{ github.repository }}
